/run/initialize
/gps/particle e-
#energy:
/gps/ene/type Gauss
/gps/ene/mono 2 GeV
/gps/ene/sigma 0 MeV


#postion:
/gps/direction 0.2493 0 0.968
/gps/position -560 0 -2800 mm


/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/radius 2 cm
/gps/pos/rot1 -0.2493 0 0.968


#angle:
/gps/ang/rot1 -0.98279 0 0.18467
/gps/ang/type iso
/gps/ang/minphi -10 deg
/gps/ang/maxphi 10 deg
/gps/ang/maxtheta 10 deg

/run/beamOn 100000
